networks:
  secure-net:
    driver: bridge
    external: true
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  jenkins:
    networks:
      secure-net:
        ipv4_address: 172.18.0.101
  nexus:
    networks:
      secure-net:
        ipv4_address: 172.18.0.101
  db:
    networks:
      - secure-net
  wiki:
    networks:
      secure-net:
        ipv4_address: 172.18.0.102